#' Split Bounding Box (source https://github.com/MatthewJWhittle/spatialutils/blob/master/R/split_bbox.R)
#'
#' Split a bounding box into an equal number of squares
#' @param bbox a bounding_box created by sf::st_bbox()
#' @param n_x the number of boxes on the x axes
#' @param n_y the number of boxes on the y axis
#' @return a list of bounding boxs generated by sf::st_bbox()
#' @import dplyr
#' @importFrom tidyr expand_grid
#' @importFrom magrittr %>%
#' @import sf
#' @importFrom purrr map

split_bbox <- function(bbox, n_x = 2, n_y = 2) {
  # Assert that bbox is a bounding box
  stopifnot(class(bbox) %in% "bbox")
  
  # Get the length of the x axis
  x_ext <- bbox["xmax"] - bbox["xmin"]
  # Get the length of the y axis
  y_ext <- bbox["ymax"] - bbox["ymin"]
  
  incr_x <- x_ext / n_x
  incr_y <- y_ext / n_y
  
  # Create a sequence of x and y coordinates to generate the xmins and ymins
  xmin <- seq(from = bbox["xmin"], to = bbox["xmax"], by = incr_x)
  ymin <- seq(from = bbox["ymin"], to = bbox["ymax"], by = incr_y)
  
  # Remove the last element of x and y to ensure that the
  # top right corner isnt create an xmin or ymin
  xmin <- xmin[1:length(xmin) - 1]
  ymin <- ymin[1:length(ymin) - 1]
  
  bbox_table <-
    expand_grid(xmin, ymin) %>%
    mutate(xmax = xmin + incr_x,
           ymax = ymin + incr_y)
  
  bounding_boxes <-
    transpose(bbox_table) %>% map( ~ .x %>%
                                     unlist %>% st_bbox(crs = st_crs(bbox)$epsg))
  
  return(bounding_boxes)
}

bbox_wrap <- function(x) st_as_sfc(st_bbox(x)) ## (https://stackoverflow.com/questions/54696440/create-polygons-representing-bounding-boxes-for-subgroups-using-sf)

roiGambia = st_read('manuscript-gambia/ee_output/roiGambia/roiGambia.shp') 

regions <- roiGambia %>%
  st_bbox() %>%
  split_bbox (n_x = 6, n_y = 2)


sf_regions <- lapply(1:length(regions), function(i) {
  regions[[i]] %>% 
    matrix(nrow = 2, byrow = TRUE) %>%
    as.data.frame() %>%
    set_names(c('lon', 'lat')) %>%
    mutate(group = i)
}) %>% do.call(what = rbind) %>%
  st_as_sf(coords=c('lon','lat'), crs=4326, remove=F) %>%
  group_by(group) %>%
  nest()%>% 
  mutate(bbox = map(data, bbox_wrap)) %>%
  `$`(bbox) %>%
  map(st_as_sf) 

sf_regions <- lapply(1:length(sf_regions), function(i){
  sf_regions[[i]]%>% mutate(group = i)
})

ggplot(sf_regions %>% do.call(what = rbind))+
  geom_sf(aes(fill = group))

